### ISSUE TITLE
 `ws` dep compilation error on iojs-v3.2.0

### ISSUE THREAD

**Issue by zdychacek** [kudos/koa-websocket#3]
Hi,

are you planning to bump version of `ws` dependecy to allow compilation under iojs v3.2.0?

I have compilation problems right now.

Everything works fine with `ws v0.8.0`.

Thank you,

O.

**Comment by kudos** [comment]
Thanks for the heads up, I just released 1.1.0.
